---
title: Compose Slides in R with Xaringan Slides
author: John Little
date: '2017-08-04'
draft: true
slug: compose-slides-in-r-with-xaringan-slides
categories:
  - R
  - Markdown
tags:
  - Xaringan
  - Reproducibility
  - Slides
  - Markdown
summary: "Xarigan Slides generate slides as a report format.  Now your analysis can creat slides at the push of a button."
---

Last week I was compelled to write about the eternal verities of [R Markdown](/post/2017-08-03-rmarkdown/).  This post entails one of the many awesome report formats -- slides -- enabled by R Markdown.  The ability to integrate slides as output of your analysis is a critical practical step in implementing reproducible data science.

> "Notably, you do not have to be a coder to take advantage of this approach."

Did you know one of the early versions of PowerPoint was initially released for the MS-DOS operating system?[^UCberkelyNews]  If I wasn't already a Xaringan Slides user I might wonder about the authoring interface for MS-DOS::PowerPoint.  Afterall, if you don't have a mouse can you even present?  Even still, we do know some fun facts and have good advice about presentation software and slide decks.

- 1984 first PowerPoint developer is hired
- 1987 PowerPoint version 1.0 public release for the Mac
- 1988 PowerPoint versions released for both Windows and MS-DOS
- 2003 Edward [Tufte hates](https://www.wired.com/2003/09/ppt2/) PowerPoint
- 2003 David [Byrne loves](https://www.wired.com/2003/09/ppt1/) PowerPoint
-  **Christopher Columbus** used slides to pitch his **goFundMe** case to Queen Isabella[^CC]
- **Abraham Lincoln** and **Google's Peter Norvig** co-athored a moving  [Cemetery Dedication at Gettysburg](http://www.norvig.com/Gettysburg/sld001.htm)
- There **is good advice** about the [art of slide design](https://speakerdeck.com/mseckington/the-art-of-slide-design)

Recently I began composing [my presentation slides](/#presentations) with a new R package, [Xaringan](https://slides.yihui.name/xaringan/) -- (pronounced *Share-in-gan*).   Authoring is easy with Xaringan because slides are composed in R Markdown.  Xaringan is optimized for RStudio so it's easy to maintain versioning and sharing via github.   Slide output is actually HTML so the the slides are easily portable on a flash drive, hosted on a laptop for presentation, or even served via any webhost (no more wondering if I have a back-up version of my slides.) 

Since the editor pane and authoring method is well integrated into R and RStudio, inserting analysis and visualization generated from R code is amazingly simple.  As such, analysis and code are part of the slide authoring process.  This integration helps maintain continuity between analysis and the final report.  Stock images are easy to insert as are any standard slide objects, all of which can be inserted with ease just like any presenter tool.  

> "If you don't have a mouse, can you even present?"  --John 226:Bostock

Visually the default slide style is spare, almost austere, but given how most slides are too cluttered (IMHO), I find this an advantage.  The installed Xaringan package comes with a standard CSS stylesheet, which can be customized to suite personal needs.  The whole slide life cycle (analysis, authoring, storing, and archiving methods) is very much inline with a tidyverse approach, thus bringing a nimble approach to reproducibility while enabling you to document your slides with literate code practices.  Notably, you do not have to be a coder to take advantage of this approach.  Xaringan slides can be authored with the same ease as with any other normal or more proprietary tools.  Just spend 20 seconds learning [R Markdown](jrljrl) **ADD LINK** and you'll be ready to increase your RQ ("Reproducibility Quotient") in no time.  

Last points.  I suspect Xaringan Slides when used within the RStudio IDE is far more satisfying than MS-DOS for PowerPoint was.  But the two systems must have striking similarities in the way that UNIX has influenced so much of modern computing.  And if you're wondering, my mouse remains a vital and relevant partner in all my quotidian slide production rituals.  Thanks be to Engelbart[^mouse].

----------
I enjoy making the slides this way.  Last week I blogged about [R Markdown](jrljrl) **ADD LINK**.  All you need to get started is R (I use the RStudio IDE and it is optimized for that environment.)  

- reproducible
- r markdown (link to previous post)
- incorporate analysis, graphs, visualizations
- very useful presentation tools (help)
- modify the appearance with CSS
- link to slide recommendations
- Visualization is a less developed passion


[^UCberkelyNews]:  http://www.berkeley.edu/news/media/releases/2005/03/08_byrne.shtml 

[^CC]: For early versions of PowerPoint, an early example project used this as an example

[^mouse]: https://en.wikipedia.org/wiki/Douglas_Engelbart